---
- name: iti lab3 - loob
  hosts: web_servers
  gather_facts: false

  vars:
    packages_to_install:
      - curl
      - vim
      - ssh

  tasks:
    - name: Update package cache (apt for Debian/Ubuntu)
      apt:
        update_cache: yes

    - name: Install latest version of packages
      package:
        name: "{{ item }}"
        state: latest
      loop: "{{ packages_to_install }}"
